version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=App.settings
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend

  redis:
    image: redis:alpine

  worker:
    build:
      context: ./backend
    command: celery -A App.myCelery worker --loglevel=info
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=App.settings
    depends_on:
      - redis
      - backend

  beat:
    build:
      context: ./backend
    command: celery -A App.myCelery beat --loglevel=info
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=App.settings
    depends_on:
      - redis
      - backend
